output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

pycodestyle:
  full: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D105
    - D205
    - D400
    - N802 # Function name should be lowercase, breaks on tests
  options:
    max-line-length: 120

pyflakes:
  disable:
    - F999

pylint:
  run: false

dodgy:
  run: true
